INSERT INTO STATUS(STATUS_ID, STATUS)
VALUES (1, 'Friendship Confirmed');
INSERT INTO STATUS(STATUS_ID, STATUS)
VALUES (2, 'Friendship Does Not Confirmed');
INSERT INTO GENRE(GENRE_ID, GENRE_NAME)
VALUES (1, 'Comedy');
INSERT INTO GENRE(GENRE_ID, GENRE_NAME)
VALUES (2, 'Drama');
INSERT INTO GENRE(GENRE_ID, GENRE_NAME)
VALUES (3, 'Cartoon');
INSERT INTO GENRE(GENRE_ID, GENRE_NAME)
VALUES (4, 'Thriller');
INSERT INTO GENRE(GENRE_ID, GENRE_NAME)
VALUES (5, 'Documentary');
INSERT INTO GENRE(GENRE_ID, GENRE_NAME)
VALUES (6, 'Action Movie');
INSERT INTO MPA(MPA_ID, MPA)
VALUES (1, 'G');
INSERT INTO MPA(MPA_ID, MPA)
VALUES (2, 'PG');
INSERT INTO MPA(MPA_ID, MPA)
VALUES (3, 'PG-13');
INSERT INTO MPA(MPA_ID, MPA)
VALUES (4, 'R');
INSERT INTO MPA(MPA_ID, MPA)
VALUES (5, 'NC-17');