DROP TABLE status IF EXISTS;

CREATE TABLE IF NOT EXISTS USERS(
ID INTEGER AUTO_INCREMENT,
NAME VARCHAR(300) NOT NULL,
LOGIN VARCHAR(300) NOT NULL,
EMAIL VARCHAR(300) NOT NULL,
BIRTHDAY DATE NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE STATUS(
STATUS_ID INTEGER NOT NULL,
STATUS VARCHAR(300),
PRIMARY KEY (STATUS_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDS(
ID_USER INTEGER,
ID_FRIEND INTEGER,
REQUEST_FOR_FRIENDSHIP VARCHAR(100),
STATUS_ID INTEGER
)


